### ISSUE TITLE
add procedure search

### ISSUE THREAD

**Issue by JohnGrossi** [JamesTiberiusKirk/team5agile#1]
add a search function for a procedure

**Comment by JohnGrossi** [comment]
a branch has been created for this

**Comment by pturtonsmith** [comment]
Could you add some more detail? What are you wanting to search by, and is this achieved by any of the existing procedures?

**Comment by JohnGrossi** [comment]
don't worry Patrick. Ross has implemented it and has been reviewed by Dumitru already
