### ISSUE TITLE
Add fields for GPS Coords

### ISSUE THREAD

**Issue by pturtonsmith** [JamesTiberiusKirk/team5agile#5]
Any issues with me adding a field/s for GPS coordinates for providers?

Anyone know if I would need separate columns for latitude and longitude?

**Comment by JohnGrossi** [comment]
yeah there shouldn't be a problem with that. It would be best for them to be in two separate columns id imagine

**Comment by pturtonsmith** [comment]
Also what's the easiest data type for you guys? What form do you get the coordinates in from google maps/whatever map api?

**Comment by pturtonsmith** [comment]
I've created two fields - provider_Latitude and provider_Longitude - as decimal(15,10). If these aren't precise enough let me know and I'll update.
They are returned automatically from existing procedures, and I'll write a procedure to add the coordinates to new & existing records.
